[package]
name = "pngv"
version = "0.2.1"
edition = "2021"
authors = ["VMASPAD"]
description = "A library and CLI tool for converting PNG images to color matrices and reconstructing them as PNG or SVG"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vmaspad/pngv"
keywords = ["png", "svg", "image", "converter", "matrix"]
categories = ["multimedia::images", "command-line-utilities"]
readme = "README.md"

[[bin]]
name = "pngv"
path = "src/main.rs"

[lib]
name = "pngv"
path = "src/lib.rs"

[dependencies]
geo = "0.21"
geo-booleanop = "0.3"
image = "0.24"
indexmap = "2.13.0"
indicatif = "0.18.4"
rayon = "1.11.0"
roxmltree = "0.21.1"
serde_json = "1.0"
svg = "0.18.0"
